# Generated by Django 5.0 on 2024-01-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
