# Generated by Django 5.0 on 2024-01-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Course',
        ),
    ]
