# Generated by Django 5.0 on 2024-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='photodata',
            fields=[
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Photo', models.CharField(max_length=100)),
            ],
        ),
    ]
