# Generated by Django 5.0 on 2024-01-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_st_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='st_course',
        ),
    ]
