# Generated by Django 5.0 on 2024-01-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_st_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='st_installment',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('t_date', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
